### ISSUE TITLE
Where can I find the source code for this library?

### ISSUE THREAD

**Issue by communig8-public** [electricimp/BG96_GPS#1]

**Comment by hfiennes** [comment]
Currently this library relies on a private API to work and hence the source is not released. The GA release of imp006 support (release 42.x) will have documented APIs for GPS location, including GPS assist features.

Until then, if you have requirements that aren't addressed by the library, let me know what you're looking for at hugo@electricimp.com

**Comment by communig8-public** [comment]
Thanks for the explanation.
